### ISSUE TITLE
Bug: limax blocks loading of angular4/webpack/aot app on iOS + Safari on MacOS

### ISSUE THREAD

**Issue by guenam** [lovell/limax#23]
My app works well on Chrome/Firefox/Edge/IE11 on Window 10 and MacOS but doesn't load on any browser tested on iOS 9.3.5 nor on Safari on MacOS, as mentioned.

No error is produced unfortunately, which makes it difficult to narrow. I spent 10 hours finding out, trying many hints: polyfill, angular versions 4.0.0, 4.0.1, 4.0.2 and many others. 

I used this project as a starter, that load without limax and doesn't with it:
https://github.com/vladotesanovic/angular2-express-starter

I'm an amateur dev and still have a lot to learn, so I may be mistaken here, but this ought to be reproducible. Let me know if you need more details.

**Comment by lovell** [comment]
Hello, my best guess is this is due to the dependency on [pinyin](https://github.com/lovell/limax/blob/master/package.json#L42), which has a native module dependency on [nodejieba](https://github.com/yanyiwu/nodejieba) that will not work properly in a browser environment.

Perhaps when "webpacked" this is including a polyfill that does not have Safari support.

If client-side support is more important than Chinese script support for your use case then perhaps consider using [speakingurl](https://github.com/pid/speakingurl).

**Comment by guenam** [comment]
Thanks for the hint, I'll look into it.

I realize I may have sounded grumpy yesterday but I'm really not: dependencies are super helpful, obviously. Sometimes they have unexpected side-effects but that's part of the game. So I keep on appreciating how useful limax is! :-)
